.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. gram_qt test_gram_qt
clean: FORCE
	$(MAKE) -C .. gram_qt_clean test_gram_qt_clean
check: FORCE
	$(MAKE) -C .. test_gram_qt_check
gram-qt gram-qt.exe: FORCE
	 $(MAKE) -C .. gram_qt
